version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: incidencias-db
    restart: always
    environment:
      MYSQL_DATABASE: incidencias-tic-instalaciones
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario
      MYSQL_ROOT_PASSWORD: rootusuario
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "usuario", "-pusuario"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 2s

  backend:
    build:
      context: ../PI-Incidencias-Backend
      dockerfile: Dockerfile
    container_name: incidencias-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/incidencias-tic-instalaciones?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: usuario
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: true
      SPRING_SQL_INIT_MODE: always
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: incidencias-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data:
